name: Сборка проекта

on:
  workflow_call:
    inputs:
      installDevDependencies:
        type: boolean
        description: Требуется ли установка devDependencies

jobs:
  build:
    name: Сборка проекта
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v2

      - name: Установка зависимостей
        run: bun install --production --ignore-scripts

      - name: Установка devDependencies
        if: inputs.installDevDependencies
        run: bun install --dev

      - name: Сборка проекта
        run: bun run build
