name: Сборка проекта

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v1

      - name: Установка зависимостей
        run: bun install --prod --ignore-scripts

      - name: Сборка проекта
        run: bun run build
