name: Тестирование

on:
  workflow_call:

jobs:
  test:
    name: Тестирование
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v1

      - name: Установка зависимостей
        run: bun install

      - name: Тестирование
        run: bun run test
