name: Тестирование

on: workflow_call

jobs:
  test:
    name: Тестирование
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v2

      - name: Установка зависимостей
        run: bun install

      - name: Тестирование
        run: bun run test
