name: Публикация на npm

on:
  workflow_call:
    inputs:
      build:
        type: boolean
        description: Требуется ли сборка при публикации
    secrets:
      NPM_TOKEN:
        required: true
        description: Токен для авторизации в npm

jobs:
  publish:
    name: Публикация на npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v2

      - name: Установка зависимостей и сборка
        if: inputs.build
        run: |
          bun install
          bun run build

      - name: Публикация
        uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          provenance: true
          token: ${{ secrets.NPM_TOKEN }}
