name: Публикация расширения VSCode

on:
  workflow_call:
    secrets:
      VSCE_PAT:
        required: true
        description: Токен для авторизации в VSCode Marketplace
      OVSX_PAT:
        required: true
        description: Токен для авторизации в Open VSX

jobs:
  publish:
    name: Публикация расширения VSCode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v2

      - name: Установка зависимостей
        run: bun install

      - name: Публикация в VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: bun run publish

      - name: Публикация в Open VSX
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: bun run publish:ovsx
