name: Публикация на npm

on:
  workflow_call:
    inputs:
      build:
        type: boolean
        description: Требуется ли сборка при публикации

jobs:
  publish:
    name: Публикация на npm
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Настройка Bun
        uses: oven-sh/setup-bun@v2

      - name: Установка зависимостей и сборка
        if: inputs.build
        run: |
          bun install
          bun run build

      - name: Публикация
        run: |
          bun install -g npm@latest # Установка последней версии npm для поддержки Trusted Publishing
          npm publish
