name: Релиз проекта

on:
  workflow_dispatch:
    inputs:
      updateType:
        description: Тип релиза
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  changelog:
    name: Релиз проекта
    uses: ExEr7um/workflows/.github/workflows/changelog.yml@main
    with:
      updateType: ${{ inputs.updateType }}
