name: Семантический заголовок PR

on: workflow_call

permissions:
  pull-requests: read

jobs:
  validate:
    name: Семантический заголовок PR
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
